#!/usr/bin/env bash

set -e

if [ -n "$DEBUG" ]; then
  set -x
fi

file="$(git rev-parse --show-toplevel)/build.yaml"

CATTLE_RANCHER_WEBHOOK_VERSION=$(yq -r -e '.webhookVersion' "$file")
CATTLE_RANCHER_PROVISIONING_CAPI_VERSION=$(yq -r -e '.provisioningCAPIVersion' "$file")
CATTLE_CSP_ADAPTER_MIN_VERSION=$(yq -r -e '.cspAdapterMinVersion' "$file")
CATTLE_DEFAULT_SHELL_VERSION=$(yq -r -e '.defaultShellVersion' "$file")
CATTLE_FLEET_VERSION=$(yq -r -e '.fleetVersion' "$file")

export CATTLE_RANCHER_WEBHOOK_VERSION
export CATTLE_RANCHER_PROVISIONING_CAPI_VERSION
export CATTLE_CSP_ADAPTER_MIN_VERSION
export CATTLE_DEFAULT_SHELL_VERSION
export CATTLE_FLEET_VERSION
